version: '3.9'

networks:
  my_network:
    driver: bridge
  

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=users
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password 
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
      - mongo_config:/data/configdb
      - ./initDB.js:/docker-entrypoint-initdb.d/initDB.js:ro
    networks:
      - my_network

  node_app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/app
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://user:password@mongo:27017/
    depends_on:
      - mongo
    networks:
      - my_network

volumes:
  mongo_db: {}
  mongo_config: {}

